DROP TABLE IF EXISTS comments cascade;
DROP TABLE IF EXISTS bookings cascade;
DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS items cascade;

CREATE TABLE IF NOT EXISTS users
(
    id int generated by default as identity primary key,
    name varchar(60) NOT NULL,
    email varchar(60) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items
(
    id int generated by default as identity primary key,
    name varchar(60) NOT NULL,
    description varchar(200) NOT NULL,
    available boolean DEFAULT TRUE NOT NULL,
    owner_id int REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    id int generated by default as identity primary key,
    date_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    date_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id int REFERENCES items (id) ON DELETE CASCADE NOT NULL,
    booker_id int REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    status varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    id int generated by default as identity primary key,
    item_id int REFERENCES items (id) ON DELETE CASCADE NOT NULL,
    author_id int REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    text varchar (400),
    date TIMESTAMP
);